struct Ngen1{
  using Value_t = int;
  static std::string name(){ return "ngen1"; }
  static std::string description(){
    return "The ngen1 parameter represents the unit number for the input data\n"
           "generated by GROUPR.  The allowable values have absolute values\n"
           "between 20 and 99, inclusively.  If the value is negative, it\n"
           "means that the file is in binary format.  If it is positive, the\n"
           "file is in plaintext. A value of 0 is also allowed.";
  }
  static bool verify( const Value_t ngen1 ){
    return ( ngen1 == 0 or argument::common::Nin::verify( ngen1 ) );
  }
};
