struct Ngen2{
  using Value_t = int;
  static std::string name(){ return "ngen2"; }
  static std::string description(){
    return "The ngen2 parameter represents the unit number for the input data\n"
           "generated by GAMINR.  The allowable values have absolute values\n"
           "between 20 and 99, inclusively.  If the value is negative, it\n"
           "means that the file is in binary format.  If it is positive, the\n"
           "file is in plaintext.";
  }
  static bool verify( const Value_t ngen2, const Value_t ngen1 ){
    return ngen2 == 0 or
           ( argument::common::Nin::verify( ngen2 ) and
             std::abs(ngen2) != std::abs(ngen1) );
  }
};
